### ISSUE TITLE
Achievements: Badges - Streaks

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#161]
Handle initial badges on app. Create bot view items and conversation files for:

- [x] Halfway to Goal on Transaction create
- [x] Implement Streak Badges
- [x] Set up `BadgeSettings` panels for streaks
- [ ] ~Implement Weekly Target Badges~ (Deferred to #453)
- [ ] ~Challenge Participation~ (Deferred to #456)
- [ ] ~Challenge Winner~ (Deferred to #128)

Winner requires polling service.

**Comment by wvictor-rr** [comment]
Broke the issue up into smaller issues
