### ISSUE TITLE
MVP Survey

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#237]
- Surveys start with a question to confirm 
- Notifications that informs the user of the survey and remind the user to complete the survey if they do not respond
- Survey is sent to users as soon as possible.
  - `Base line` - 1 day after registration
  - `EA Tool` - 3 days after Registration
- In order to win Pulsa, the user needs to have the `Base line` and `EA Tool` completed.
- We need to investigate how we can view/export the data from Wagtail

### TODOS

- [x] Persist Survey
- [x] Submit drafts with each user answer
- [x] Store consent boolean in submission draft in a way that reports can aggregate its user count
  - eg. X number of users did not consent to take the survey
- [x] When user has submitting, the Bot should restrict access to that survey so users don't take it again
