### ISSUE TITLE
Production Release Checklist

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#397]
- [x] Privacy Policy Hosting
- [ ] ~Outstanding Translations~ (Deferred to #460)
- [ ] ~Upload Images~ (Deferred to #458)
- [ ] ~Enter Tip Articles~(Deferred to #459)
- [x] Enter Badges
