### ISSUE TITLE
Release 0.1.2 Checklist

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#533]
### Content

- [x] Update Surveys in QA server with new consent questions
- [x] Create Surveys on Production server
- [ ] ~Ensure Terms & Conditions on Production server is served under correct URL (`/agreements/terms-conditions/`)~ The `SurveyIndex` and `AgreementIndex` models are not on the production server yet
- [x] Version bump (waiting for outstanding issue PRs)

### Translations

- [ ] ~Survey Consent questions~
- [ ] ~Challenge Winner Push Notification text, Content and Translation~
- [ ] ~All outstanding translations on Instruction Text spreadsheet~

**Note:** Translations delayed. Will be handled along with QA release feedback https://github.com/praekeltfoundation/gem-bbb-indo/issues/460
